<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Waktu Akhir Kp_SuratPermohonanKpwaktu_85727c</name>
   <tag></tag>
   <elementGuidId>ee104eb4-09b8-4025-9cef-64d92feafbd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='suratpermohonankp-waktu_akhir_kp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#suratpermohonankp-waktu_akhir_kp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Waktu Akhir Kp&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>95f72418-17e7-45bb-8579-83226738d695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>008bde74-b595-4836-b30c-a5089065ff4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>suratpermohonankp-waktu_akhir_kp</value>
      <webElementGuid>0fe14b37-4829-4334-b11b-39482819a3db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control hasDatepicker</value>
      <webElementGuid>97afc31e-2bc5-4b89-82a2-eeba3f7ab0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SuratPermohonanKp[waktu_akhir_kp]</value>
      <webElementGuid>3cb6912d-6153-4464-af54-e66fcc6159a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suratpermohonankp-waktu_akhir_kp&quot;)</value>
      <webElementGuid>4150f6b0-fba2-4b00-aec4-94093cf880da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='suratpermohonankp-waktu_akhir_kp']</value>
      <webElementGuid>33179e9f-e726-4a10-b2ff-c7ef6eea13ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[4]/div/input</value>
      <webElementGuid>9baa9dff-566d-4874-9c34-2d82a031ea5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>ae6e762f-1104-4429-8913-f11e356dda3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'suratpermohonankp-waktu_akhir_kp' and @name = 'SuratPermohonanKp[waktu_akhir_kp]']</value>
      <webElementGuid>6b0487db-1fda-4940-b3c5-2e83cd8b70af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
