<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Waktu Awal Kp_SuratPermohonanKpwaktu_awal_kp</name>
   <tag></tag>
   <elementGuidId>3639f4f0-7443-4e68-977b-8c02cd589758</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='suratpermohonankp-waktu_awal_kp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#suratpermohonankp-waktu_awal_kp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Waktu Awal Kp&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>450c07b4-25f0-486a-b1b4-cc753f2a074f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d4f9cbd4-67e1-49fe-a046-28eda8e614c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>suratpermohonankp-waktu_awal_kp</value>
      <webElementGuid>5b5705a5-becf-42f7-885d-58abd159afb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control hasDatepicker</value>
      <webElementGuid>b1ce2dfd-b710-4066-bdca-abfe3a0685d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SuratPermohonanKp[waktu_awal_kp]</value>
      <webElementGuid>9f6a0509-5190-43e5-a392-59c6b2e4a777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suratpermohonankp-waktu_awal_kp&quot;)</value>
      <webElementGuid>edcd3672-67a9-4321-a494-c45bad4acf39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='suratpermohonankp-waktu_awal_kp']</value>
      <webElementGuid>86679ce3-a219-4c03-8e59-0e722c80a0b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[3]/div/input</value>
      <webElementGuid>4315ea83-5605-4f0f-87a6-aea714bfda47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>b9be71f3-7c7e-4f58-ba55-dd38de0f19c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'suratpermohonankp-waktu_awal_kp' and @name = 'SuratPermohonanKp[waktu_awal_kp]']</value>
      <webElementGuid>894e9cfd-ac78-475f-8247-2d57fa31696d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
