<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Nama Tujuan_SuratPermohonanKpnama_tujuan</name>
   <tag></tag>
   <elementGuidId>8d845d4c-1b89-4657-854d-51e24408be14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='suratpermohonankp-nama_tujuan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#suratpermohonankp-nama_tujuan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Nama Tujuan&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>fbe471bc-1c51-4cef-a7d3-663ea0b2b31d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>suratpermohonankp-nama_tujuan</value>
      <webElementGuid>791e2c9d-64cb-4f71-b2c8-2ee5a8f21720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>77ce64c3-6673-4319-95a5-97e440b45d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SuratPermohonanKp[nama_tujuan]</value>
      <webElementGuid>5923dff7-775e-4b99-80c2-d27a761c1c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>11793c31-cf91-4d52-ad6a-f1d4767ff25f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suratpermohonankp-nama_tujuan&quot;)</value>
      <webElementGuid>f20324ab-2b89-424a-953a-d617dc29c53b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='suratpermohonankp-nama_tujuan']</value>
      <webElementGuid>70487886-9a6d-48c2-a736-cd0e06244ba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div/div/textarea</value>
      <webElementGuid>620d64c8-669f-43d6-831b-e604abea4bc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>bca6e609-6f86-47e5-8ea1-b8f6062bf9fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'suratpermohonankp-nama_tujuan' and @name = 'SuratPermohonanKp[nama_tujuan]']</value>
      <webElementGuid>9dd05abe-58fa-40f6-a614-7616f284e376</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
