<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal Sidang TA_SuratKeteranganLulu_1829b1</name>
   <tag></tag>
   <elementGuidId>4832584e-3020-44c9-81ef-545df16d087f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='suratketeranganlulus-tanggal_sidang_ta']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#suratketeranganlulus-tanggal_sidang_ta</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Tanggal Sidang TA&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ab3dba9-03f7-470b-a2ec-4a19fb333fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>51773fdd-3957-423e-8eb2-08f7f78a6b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>suratketeranganlulus-tanggal_sidang_ta</value>
      <webElementGuid>b56345e7-7831-428e-b09a-78f65bb82f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control hasDatepicker</value>
      <webElementGuid>844a003c-8d7a-4390-ab92-f680f4e366ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SuratKeteranganLulus[tanggal_sidang_ta]</value>
      <webElementGuid>af871dac-8879-4c52-b7ca-bc0982b591d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suratketeranganlulus-tanggal_sidang_ta&quot;)</value>
      <webElementGuid>0ccc1dac-1a49-4853-bd47-f3902c41ff8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='suratketeranganlulus-tanggal_sidang_ta']</value>
      <webElementGuid>52696deb-1583-4af7-998e-5923415c6058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[2]/div/input</value>
      <webElementGuid>5fabd6bf-8b01-4bb3-afe0-1ca137168942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>ed0482e3-c296-4904-b91d-b848250918da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'suratketeranganlulus-tanggal_sidang_ta' and @name = 'SuratKeteranganLulus[tanggal_sidang_ta]']</value>
      <webElementGuid>dfe81f11-4756-430a-badb-34d9fb6e355e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
