<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rencana Berangkat_IzinKeluarrencana_b_bd1150</name>
   <tag></tag>
   <elementGuidId>cc7468c2-b677-47d8-a540-d5374d6f8716</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='izinkeluar-rencana_berangkat']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#izinkeluar-rencana_berangkat</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Rencana Berangkat&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5aad454a-f642-4085-b2df-6be99222fb7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>06d4aaaf-a381-4d31-a6fa-86b328844031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>izinkeluar-rencana_berangkat</value>
      <webElementGuid>b9737748-ee1c-4db0-ad3a-f69790e385b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-ms</value>
      <webElementGuid>7dae89c0-2cdd-456d-a739-8c39c7fe24cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IzinKeluar[rencana_berangkat]</value>
      <webElementGuid>21aaad05-4de8-4202-9310-18a9e0cfb928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>c584080b-d9ad-44d3-b9c5-88e179910af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;izinkeluar-rencana_berangkat&quot;)</value>
      <webElementGuid>fc29f6ee-4dd9-4fac-be40-a6a4f7797203</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='izinkeluar-rencana_berangkat']</value>
      <webElementGuid>b4224bf0-ae0e-4db8-88f3-5f4598563a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div/div/div/div/input</value>
      <webElementGuid>93b913e7-e98e-4dfa-ba1c-b07c8bc5d4b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>e439467c-8ee5-47df-9952-46333827f617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'izinkeluar-rencana_berangkat' and @name = 'IzinKeluar[rencana_berangkat]']</value>
      <webElementGuid>821d665b-d874-4461-93ce-6c9b3b73fd2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
