<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rencana Kembali_IzinKeluarrencana_kembali</name>
   <tag></tag>
   <elementGuidId>20220e44-4f16-4da9-86d7-9f0d9c813020</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='izinkeluar-rencana_kembali']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#izinkeluar-rencana_kembali</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Rencana Kembali&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>59aeb0bb-aa1e-4276-aa10-280253c2c252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>17d1a724-69cf-401f-a2b3-e730a453b756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>izinkeluar-rencana_kembali</value>
      <webElementGuid>8ad7606f-ca6c-4b3e-b256-62db27c50c98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-ms</value>
      <webElementGuid>f474bbc1-1690-455e-aa17-5e617d8cfdfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IzinKeluar[rencana_kembali]</value>
      <webElementGuid>c667da79-728a-4331-a0c4-5b5cbe04410b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>705a5b4d-7896-4278-a37b-aac032cd6ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;izinkeluar-rencana_kembali&quot;)</value>
      <webElementGuid>e9c54216-2ea2-46dd-ac19-6fd34f262e1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='izinkeluar-rencana_kembali']</value>
      <webElementGuid>59153f02-3aec-4c8a-a864-0e205411e845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div/div[2]/div/div/input</value>
      <webElementGuid>d41b9b37-372e-4a69-9ebe-ff6a12f335df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>da75abe4-8dcf-4383-a7db-2f30d1282df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'izinkeluar-rencana_kembali' and @name = 'IzinKeluar[rencana_kembali]']</value>
      <webElementGuid>6d7cf01c-9d6d-4d5c-b96d-6f1399daddf0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
