<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tahun MBKM_SuratRekomendasiMbkmtahun_mbkm</name>
   <tag></tag>
   <elementGuidId>2f0bbb0f-309f-47f8-a089-cde0b0087a44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='suratrekomendasimbkm-tahun_mbkm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#suratrekomendasimbkm-tahun_mbkm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Tahun MBKM&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>55589092-d074-44bf-bab8-00331b8851a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b33ec292-f83d-4272-a758-28a1301a2926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>suratrekomendasimbkm-tahun_mbkm</value>
      <webElementGuid>73056c9e-c343-408d-acb0-b1a84f4cd340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b2c22489-377a-481c-b691-6205e6d6d59b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SuratRekomendasiMbkm[tahun_mbkm]</value>
      <webElementGuid>ac861d32-1f7a-40b1-9c23-dc03bfd4a595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suratrekomendasimbkm-tahun_mbkm&quot;)</value>
      <webElementGuid>031ea593-f0bc-4543-8b58-46a9782c6534</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='suratrekomendasimbkm-tahun_mbkm']</value>
      <webElementGuid>9d051997-a0d4-4c34-9d54-db07076f62f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[2]/div/input</value>
      <webElementGuid>30d5e277-baed-4d85-9820-c6d009d3ac2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>e84b3ed1-656c-4e6b-bc79-d7d9e50c3a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'suratrekomendasimbkm-tahun_mbkm' and @name = 'SuratRekomendasiMbkm[tahun_mbkm]']</value>
      <webElementGuid>9ea52aae-f6f2-4864-ac92-9d6d0ce46d98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
