<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Angkatan MBKM_SuratRekomendasiMbkmang_0fea94</name>
   <tag></tag>
   <elementGuidId>0c3548a6-5846-48d7-975c-28bdb053f7d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='suratrekomendasimbkm-angkatan_mbkm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#suratrekomendasimbkm-angkatan_mbkm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Angkatan MBKM&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>95674298-cf30-49d5-bba3-95434fd34b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e251d8ef-3364-4db0-b494-43538bb2717b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>suratrekomendasimbkm-angkatan_mbkm</value>
      <webElementGuid>92224a36-d482-4fd9-b28a-c65940e37bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>281e399c-6958-4fb8-a514-818e885acc5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SuratRekomendasiMbkm[angkatan_mbkm]</value>
      <webElementGuid>b42a6280-a8d1-4641-83d8-8262dd726b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suratrekomendasimbkm-angkatan_mbkm&quot;)</value>
      <webElementGuid>20ef00a6-e07e-447d-95b7-3f4c279d9666</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='suratrekomendasimbkm-angkatan_mbkm']</value>
      <webElementGuid>b78c5578-a68d-48a6-bedd-4c198c4596a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div/div/input</value>
      <webElementGuid>66e7e550-39de-4b76-8fca-80e8f290c271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>041e8cc5-7a32-4a65-a8b1-4e7c66707fd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'suratrekomendasimbkm-angkatan_mbkm' and @name = 'SuratRekomendasiMbkm[angkatan_mbkm]']</value>
      <webElementGuid>1caf441c-d4b9-4600-8a3f-a2b9d863ca63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
