<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rencana Berakhir_IzinKolaboratifrenca_cc4134</name>
   <tag></tag>
   <elementGuidId>5a90c43c-711e-4108-8be9-6fa83e548f22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='izinkolaboratif-rencana_berakhir']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#izinkolaboratif-rencana_berakhir</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Rencana Berakhir&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6b2f310-167d-4038-8583-e41db7d17c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>216e6ba5-abb9-4135-b6ef-273e7f89047c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>izinkolaboratif-rencana_berakhir</value>
      <webElementGuid>75bd460a-24a0-4972-b024-cb071cc19576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-ms</value>
      <webElementGuid>cf64e16e-d631-4e9c-a7a7-9f96a70f92ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IzinKolaboratif[rencana_berakhir]</value>
      <webElementGuid>e72df38f-4e63-4bc3-907e-58767bbb0ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>19325da7-1ca3-476d-a11d-4524ccce006c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;izinkolaboratif-rencana_berakhir&quot;)</value>
      <webElementGuid>46445732-f0d3-475a-a213-b25e2f2ca1f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='izinkolaboratif-rencana_berakhir']</value>
      <webElementGuid>d5b0e6e7-5f98-4bb6-b1a6-bb5a1d0f73c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div/div[2]/div/div/input</value>
      <webElementGuid>0597e4a8-1b29-4a5d-ba2c-c5b65d2afe56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>e434b9ad-592f-4d5b-9d4a-628907d453c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'izinkolaboratif-rencana_berakhir' and @name = 'IzinKolaboratif[rencana_berakhir]']</value>
      <webElementGuid>d12f411d-494f-45b8-8bfe-365b11b96414</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
