<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Batas Waktu_IzinKolaboratifbatas_waktu</name>
   <tag></tag>
   <elementGuidId>6ef6c768-f63c-4af6-a794-8e0a63a3eacc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='izinkolaboratif-batas_waktu']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#izinkolaboratif-batas_waktu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Batas Waktu&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9428dca-af2d-4191-9754-57c35ffb1b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9715b240-9b1e-4731-a822-dfe8323de9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>izinkolaboratif-batas_waktu</value>
      <webElementGuid>be5b1c4e-40b9-4452-a20d-bd014634883f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-ms</value>
      <webElementGuid>8649a688-cbec-4213-806c-2e4a69b2056b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IzinKolaboratif[batas_waktu]</value>
      <webElementGuid>61c8ff81-c275-4a39-9f2a-30404bf330c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>a9825766-6a6d-49b0-96ee-bbbccf2402ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;izinkolaboratif-batas_waktu&quot;)</value>
      <webElementGuid>6cdcbe85-137d-4654-ae78-721a9fa6d02e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='izinkolaboratif-batas_waktu']</value>
      <webElementGuid>1eacaad9-b44b-4392-8e6d-0363a881ff87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div/div[3]/div/div/input</value>
      <webElementGuid>f09bf65c-6003-4faf-80a6-2a7ddaeb8ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>f8eea067-5064-43d8-8c9c-d058a28aaa35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'izinkolaboratif-batas_waktu' and @name = 'IzinKolaboratif[batas_waktu]']</value>
      <webElementGuid>52627400-11b8-44dd-9e14-1ed128778854</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
