<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Waktu Awal Magang_SuratMagangwaktu_aw_f1237f</name>
   <tag></tag>
   <elementGuidId>3ba3eedc-1cd1-4c2b-a9f0-3c71f21c6820</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='suratmagang-waktu_awal_magang']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#suratmagang-waktu_awal_magang</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Waktu Awal Magang&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2211629d-5123-4e65-b3cc-9684cf0965ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>02333869-657e-498a-a924-f7c716194098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>suratmagang-waktu_awal_magang</value>
      <webElementGuid>5f050570-d9d6-4efd-948e-30f6a6b37fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control hasDatepicker</value>
      <webElementGuid>a24d620d-99df-4937-8a4f-028684601adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SuratMagang[waktu_awal_magang]</value>
      <webElementGuid>bb5fe86f-4d34-41be-afbf-3670adc616e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suratmagang-waktu_awal_magang&quot;)</value>
      <webElementGuid>0229653c-9b8c-4f11-a64b-009ad9475c0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='suratmagang-waktu_awal_magang']</value>
      <webElementGuid>98f9423f-0f0e-40e9-a57e-0eb50a2b67d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[3]/div/input</value>
      <webElementGuid>256a02c6-3299-49e9-92b1-26ee85170480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>60656ec3-ffc7-4f22-a0e6-0e3853719149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'suratmagang-waktu_awal_magang' and @name = 'SuratMagang[waktu_awal_magang]']</value>
      <webElementGuid>f3d1c7f4-c44f-494a-9988-a65000aa1185</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
