<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Waktu Akhir Magang_SuratMagangwaktu_a_aba586</name>
   <tag></tag>
   <elementGuidId>2730ee52-e55e-4202-a4b6-2723aff536e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='suratmagang-waktu_akhir_magang']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#suratmagang-waktu_akhir_magang</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Waktu Akhir Magang&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e13d273-a4b5-43bd-b043-8786e78bfaae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>394a7c2f-f592-4f38-9ccc-147512c444d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>suratmagang-waktu_akhir_magang</value>
      <webElementGuid>77b9ef30-b8b5-4297-9c31-139e8c185106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control hasDatepicker</value>
      <webElementGuid>ac1e04a0-a9ad-4b5e-9005-4363e1480fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SuratMagang[waktu_akhir_magang]</value>
      <webElementGuid>115c5199-f8c4-4611-a6ff-d958de1d1ad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suratmagang-waktu_akhir_magang&quot;)</value>
      <webElementGuid>64d92390-003d-4ced-9ef0-0522d05b9aa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='suratmagang-waktu_akhir_magang']</value>
      <webElementGuid>4392beb2-65d4-4b27-a74b-8c5160ed120f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[4]/div/input</value>
      <webElementGuid>af1f0e48-5a77-47e4-a2b9-e0c7ded5beb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>7e77a3a3-ce35-4ca3-b28b-e41bf93face6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'suratmagang-waktu_akhir_magang' and @name = 'SuratMagang[waktu_akhir_magang]']</value>
      <webElementGuid>ea01e768-de5d-4469-9918-ef65b1ace106</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
