<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rencana Mulai_IzinRuanganrencana_mulai</name>
   <tag></tag>
   <elementGuidId>57f1c846-4394-4633-a300-d77d06be1ed5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='izinruangan-rencana_mulai']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#izinruangan-rencana_mulai</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Rencana Mulai&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60b3c54e-a8c6-47be-86ca-0a4fa44a8112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b4578966-229c-47a7-946e-57ed244e8eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>izinruangan-rencana_mulai</value>
      <webElementGuid>00906c5c-ca36-42cd-8798-d1f5306c9e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-ms</value>
      <webElementGuid>429a2c95-3856-4c0b-9edf-1d653ce51798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IzinRuangan[rencana_mulai]</value>
      <webElementGuid>873cb462-6622-4376-a9a0-a27435848db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>1356f0f2-beae-4d28-9147-2f6091decf37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;izinruangan-rencana_mulai&quot;)</value>
      <webElementGuid>303f02af-22fb-4b21-89f9-9d0a05317844</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='izinruangan-rencana_mulai']</value>
      <webElementGuid>724bcc32-9a8c-4045-82dd-331b6b2a9e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div/div/div/div/input</value>
      <webElementGuid>3ca609cd-633f-447f-a996-b08e44b9a57f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>f0b441d4-502c-4b01-91e5-ef88a2c1c41e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'izinruangan-rencana_mulai' and @name = 'IzinRuangan[rencana_mulai]']</value>
      <webElementGuid>28a5071d-564a-4f5c-ad66-97dd5c7e4a18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
