<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rencana Berakhir_IzinRuanganrencana_berakhir</name>
   <tag></tag>
   <elementGuidId>ef7b34f0-4b13-461d-9cb2-78564ae4b297</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='izinruangan-rencana_berakhir']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#izinruangan-rencana_berakhir</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Rencana Berakhir&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f07071d-4cb3-4eac-a07b-324d9b24e31d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c45e2ad0-bdde-4a9a-8942-ed3a8538b131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>izinruangan-rencana_berakhir</value>
      <webElementGuid>2352fa85-e796-4677-b078-ff313ff352ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-ms</value>
      <webElementGuid>7efee52f-7275-4f1f-a2c8-fc70b3f6cc28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IzinRuangan[rencana_berakhir]</value>
      <webElementGuid>d2df0311-bb51-4880-b9c6-e20a53ac88e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>63e8354f-5425-4a84-aab5-5cb4799b22b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;izinruangan-rencana_berakhir&quot;)</value>
      <webElementGuid>a453a65b-f0e5-4955-9962-e030284486f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='izinruangan-rencana_berakhir']</value>
      <webElementGuid>3d5e1cef-d62c-4dcc-b8f1-395a5a0f9028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div/div[2]/div/div/input</value>
      <webElementGuid>34c40f4d-ee5d-4b44-8fb2-8faafbdcf90a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>c6de53a9-e83c-438c-b9d6-93faed0ed860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'izinruangan-rencana_berakhir' and @name = 'IzinRuangan[rencana_berakhir]']</value>
      <webElementGuid>a85a82d4-fc30-4510-af81-078f88714cc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
