<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Request</name>
   <tag></tag>
   <elementGuidId>706ae185-859d-4071-852d-344b165066bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='main-content']/div/p/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-success</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Request&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0028f105-fe9e-4170-b835-1af90f054e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>363fecd8-0d01-4682-b088-1286d5cc4f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/askm/izin-ruangan/izin-by-mahasiswa-add</value>
      <webElementGuid>0b15793a-afbc-401c-9e18-a3c509bf8cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Request</value>
      <webElementGuid>ea63f05b-587c-4a58-b5f9-c150a8896163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;izin-ruangan-index&quot;]/p[1]/a[@class=&quot;btn btn-success&quot;]</value>
      <webElementGuid>693ea122-203f-4c56-ae91-58e3a35044e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-content']/div/p/a</value>
      <webElementGuid>3aad8b5b-b41e-44fd-8ea7-3d5c736a8cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Request')])[2]</value>
      <webElementGuid>35b4ccef-0768-40ad-b616-92d37af76228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Izin Penggunaan Ruangan'])[3]/following::a[1]</value>
      <webElementGuid>67057e3d-81a4-434e-bf7b-eda9eef0d752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Izin Penggunaan Ruangan'])[2]/following::a[1]</value>
      <webElementGuid>2b6a1958-a9f9-4b81-91d5-58e7d022da4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Izin Saya'])[1]/preceding::a[1]</value>
      <webElementGuid>789bc86a-a72b-4d19-b998-e2e7cd976af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hari ini'])[1]/preceding::a[2]</value>
      <webElementGuid>6d8ad872-008d-4d00-acea-2e5437221044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Request']/parent::*</value>
      <webElementGuid>b6201f95-8ef1-47c2-8a4b-e1855bd55a0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/askm/izin-ruangan/izin-by-mahasiswa-add')]</value>
      <webElementGuid>538cd14c-6d24-4545-bb46-ef8ee7c9b18f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>4da3d090-25ee-468c-89e2-6ae50819d281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/askm/izin-ruangan/izin-by-mahasiswa-add' and (text() = 'Request' or . = 'Request')]</value>
      <webElementGuid>2bd5b1a4-8614-4204-966e-db5b927b6bfe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
