<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Alamat Tempat_SuratPengantarProyek_c258c5</name>
   <tag></tag>
   <elementGuidId>688a751f-2c20-435b-8559-89b635a95ac3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='suratpengantarproyek-alamat_tujuan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#suratpengantarproyek-alamat_tujuan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Alamat Tempat&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9a8a37a5-1b15-4cba-a129-b6c85a69afcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>suratpengantarproyek-alamat_tujuan</value>
      <webElementGuid>bfae76ff-4b51-4c99-ba3b-ecd7565abfb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>80a8d747-f685-46b1-b848-b312dac98315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SuratPengantarProyek[alamat_tujuan]</value>
      <webElementGuid>fd0fec54-28eb-4bcd-ae87-2b3ab6aef087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>d19dcca5-251c-4e3c-9285-4e2e4c468dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1d6dc1ad-cbb3-449d-96aa-d787adb6f732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suratpengantarproyek-alamat_tujuan&quot;)</value>
      <webElementGuid>30a12639-da4b-4e07-ab38-b26015ca8215</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='suratpengantarproyek-alamat_tujuan']</value>
      <webElementGuid>2296b115-b71c-4f93-9119-5174ebe80330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[2]/div/textarea</value>
      <webElementGuid>f2b3a2be-0ebb-41df-9c76-7160e110f324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>b5bb97ea-6343-4a45-a8f2-bc20eeb39df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'suratpengantarproyek-alamat_tujuan' and @name = 'SuratPengantarProyek[alamat_tujuan]']</value>
      <webElementGuid>19f31ad7-7ffb-422e-bf96-de9a1c303c16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
