<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Request IB</name>
   <tag></tag>
   <elementGuidId>d7d740b8-38e6-4e70-ae56-ee562722546e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='main-content']/div/div[3]/div/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.toolbar-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Request IB&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4590a0a0-5869-4d20-80b4-0d2e00be4971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toolbar-label</value>
      <webElementGuid>24104638-acf0-4f08-ae1a-0cef1de16c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Request IB</value>
      <webElementGuid>d2e56270-076a-4378-b18b-8b70ca6d9634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;izin-bermalam-index&quot;]/div[@class=&quot;btn-toolbar sysx-toolbar&quot;]/div[@class=&quot;btn-group btn-group-sm&quot;]/a[@class=&quot;btn btn-success&quot;]/span[@class=&quot;toolbar-label&quot;]</value>
      <webElementGuid>f7631872-f824-4655-bd5e-9a6a6d267a64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-content']/div/div[3]/div/a/span</value>
      <webElementGuid>1d4afd3e-431a-48be-865e-7e5d78074993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Izin Bermalam'])[4]/following::span[1]</value>
      <webElementGuid>859474a9-97d9-4ed6-9241-4ec3abbe1443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Izin Bermalam'])[3]/following::span[1]</value>
      <webElementGuid>0c802b4a-5ab6-47e3-812c-709b42559e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request sebelumnya'])[1]/preceding::span[1]</value>
      <webElementGuid>d17857ff-0a84-42a1-aad0-33534ad3c22d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Request IB']/parent::*</value>
      <webElementGuid>3bc740b0-1f84-40fd-88eb-a7a8fb856fdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/span</value>
      <webElementGuid>8f5a256a-d8e6-4438-84fb-66234fd96295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Request IB' or . = 'Request IB')]</value>
      <webElementGuid>8f96b6e4-f602-4c77-b47a-3996edc633e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
