<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Alamat Instansi_SuratPengantarTaal_e43310</name>
   <tag></tag>
   <elementGuidId>6ad60767-7c71-42db-bcae-a0d78e4b5295</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='suratpengantarta-alamat_instansi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#suratpengantarta-alamat_instansi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Alamat Instansi&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c9ffb9d9-c06d-4c21-8689-b47c0283d29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>suratpengantarta-alamat_instansi</value>
      <webElementGuid>25cd55a8-b9fb-4410-bcde-3d99908d2646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>95eaeb7b-0be5-44d7-9db8-7f96c0e97360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SuratPengantarTa[alamat_instansi]</value>
      <webElementGuid>02a1c70c-8cb1-4c43-b5a0-e391ee8deb49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>47da77a7-da91-4101-a914-f73a36a8996e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suratpengantarta-alamat_instansi&quot;)</value>
      <webElementGuid>7bf3ae2e-0bb2-4363-8353-430164daa546</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='suratpengantarta-alamat_instansi']</value>
      <webElementGuid>51ea6c99-b22a-44eb-a42f-c702f2da8bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[2]/div/textarea</value>
      <webElementGuid>62391140-a816-4aca-8c8a-ebf64d8a4dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>8430676f-b919-421b-b3fe-8023b3697e00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'suratpengantarta-alamat_instansi' and @name = 'SuratPengantarTa[alamat_instansi]']</value>
      <webElementGuid>f375f0ee-8b86-4e21-96be-509a0cd6753d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
