<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Informasi  Data yang diminta_Surat_9098d8</name>
   <tag></tag>
   <elementGuidId>3f4fa0de-3f4b-4d5f-81d1-04f2e3eb04f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='suratpengantarta-informasi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#suratpengantarta-informasi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Informasi / Data yang diminta&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>87935dad-0a11-426a-b185-8a0ffc03355c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>suratpengantarta-informasi</value>
      <webElementGuid>6cfbdecf-9a42-410a-aaa9-e53a30e300d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ec2a72c7-7b4e-41ce-9767-a3f529b77d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SuratPengantarTa[informasi]</value>
      <webElementGuid>4023b6cc-10e3-44e3-861d-81875c19e3d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>e4f3a92a-7b24-495b-8de2-b25e69a109c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suratpengantarta-informasi&quot;)</value>
      <webElementGuid>dc11da1a-34c1-4128-a82e-49c6ece39b56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='suratpengantarta-informasi']</value>
      <webElementGuid>c57554c0-9622-4fba-8236-b25f0f0d08e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[3]/div/textarea</value>
      <webElementGuid>8ac794e0-4030-47a3-8257-31b24f1fd1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/textarea</value>
      <webElementGuid>37ce4596-1b3b-4b12-9278-20cfd129e697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'suratpengantarta-informasi' and @name = 'SuratPengantarTa[informasi]']</value>
      <webElementGuid>fbfb580f-b3a8-41a2-b63b-eff9bf9e0bfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
