<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Alamat Tujuan Surat_SuratLombaalam_26022e</name>
   <tag></tag>
   <elementGuidId>41755d6b-02c9-44d0-b74e-4ffd0f89e067</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='suratlomba-alamat_tujuan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#suratlomba-alamat_tujuan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Alamat Tujuan Surat&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9868696e-3d38-409b-8f6a-ff04b7ee70b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>suratlomba-alamat_tujuan</value>
      <webElementGuid>73e05670-8205-4b7c-ac48-0288973171fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>765ef7d4-7267-4877-b8c9-2c1889b0fe8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SuratLomba[alamat_tujuan]</value>
      <webElementGuid>8c43673a-5ffb-478f-935b-cc51d8b5bc30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>e50cf78b-e669-4a8f-834b-8782efcf6a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5146d0e8-8f04-4dbb-a82c-c8c9dc768031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suratlomba-alamat_tujuan&quot;)</value>
      <webElementGuid>a87c1be0-1515-4dbb-8757-34ec301b110e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='suratlomba-alamat_tujuan']</value>
      <webElementGuid>c15f1668-ddd6-477a-bb67-0c1cf1cfe621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div[2]/div/textarea</value>
      <webElementGuid>3580bdb0-d804-441b-990c-1c764366922c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>dc4bee7c-b18e-4671-9e8d-b5cf3948085a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'suratlomba-alamat_tujuan' and @name = 'SuratLomba[alamat_tujuan]']</value>
      <webElementGuid>7855674d-1c7e-4462-b99e-cecdd1fd4352</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
